In [1]:
from controller.database_controller import DatabaseController
import numpy as np
DB_PATH = r"..\data\database.db"

In [2]:
db = DatabaseController(DB_PATH)

Create db connection at: D:\myDocs\Apprentissage\Isep\Year_3\Brno-Privacy_Preserving_Face_Recognition_Project\data\database.db


In [3]:
db.get_user_id_list()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 25,
 26,
 27]

In [4]:
res = db.get_user(1)
print(f"type: {type(res)}")
print(f"shape: {res.shape}")
print("--- Inside numpy.ndarray ---")
print(f"type: {type(res[0])}")
print(f"len: {len(res[0])}")
print(f"res: {(res[0])[:100]}")

type: <class 'numpy.ndarray'>
shape: (11,)
--- Inside numpy.ndarray ---
type: <class 'numpy.str_'>
len: 7468
res: /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAx


In [5]:
res = db.get_table()
print(f"type: {type(res)}")
print(f"len: {len(res)}")
print("--- Inside list ---")
print(f"type: {type(res[0])}")
print(f"len: {len(res[0])}")
print(f"res: {(res[0][0], res[0][1][:100])}")

type: <class 'list'>
len: 24
--- Inside list ---
type: <class 'tuple'>
len: 2
res: (1, '["/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLD')


In [6]:
res = db.get_user_vectors()
print(f"type: {type(res)}")
print(f"len: {len(res)}")
print(f"res: {res[0][:100]}")

type: <class 'list'>
len: 24
res: ["/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLD


In [7]:
# Add user
data1 = np.random.rand(4, 3)
print("Original array 1:\n", data1)
user_id = db.add_user(data1)
print("User id is:", user_id)

# Modifie user
data2 = np.random.rand(4, 3)
print("Original array 2:\n", data2)
res = db.update_user(user_id, data2)
print("Number of affected rows:", res)
retrieved_array = db.get_user(user_id)
print("Both arrays not match:", data1==retrieved_array)

# Delete user
res = db.delete_user(user_id)
print("Delete user:", user_id)
print("Number of affected rows:", res)

Original array 1:
 [[0.52872222 0.50186776 0.59049472]
 [0.88806945 0.49559459 0.58509991]
 [0.94870323 0.35795047 0.58484173]
 [0.54047736 0.98855962 0.50216823]]
User id is: 28
Original array 2:
 [[0.85697029 0.29510131 0.07755905]
 [0.81808869 0.64313387 0.26421066]
 [0.03464701 0.75737123 0.90586631]
 [0.57756693 0.43897927 0.68741193]]
Number of affected rows: 1
Both arrays not match: [[False False False]
 [False False False]
 [False False False]
 [False False False]]
Delete user: 28
Number of affected rows: 1
