In [2]:
from controller.database_controller import DatabaseController
import numpy as np
DB_PATH = r"..\data\gui_database.db"

In [3]:
db = DatabaseController(DB_PATH)

Create db connection at: D:\myDocs\Apprentissage\Isep\Year_3\Brno-Privacy_Preserving_Face_Recognition_Project\data\database.db


In [4]:
db.get_user_id_list()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 25,
 26,
 27,
 29,
 30,
 31,
 32,
 33,
 35,
 36,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48]

In [5]:
res = db.get_user(1)
print(f"type: {type(res)}")
print(f"shape: {res.shape}")
print("--- Inside numpy.ndarray ---")
print(f"type: {type(res[0])}")
print(f"len: {len(res[0])}")
print(f"res: {(res[0])[:100]}")

type: <class 'numpy.ndarray'>
shape: (11,)
--- Inside numpy.ndarray ---
type: <class 'numpy.str_'>
len: 7468
res: /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAx


In [6]:
res = db.get_table()
print(f"type: {type(res)}")
print(f"len: {len(res)}")
print("--- Inside list ---")
print(f"type: {type(res[0])}")
print(f"len: {len(res[0])}")
print(f"res: {(res[0][0], res[0][1][:100])}")

type: <class 'list'>
len: 42
--- Inside list ---
type: <class 'tuple'>
len: 2
res: (1, '["/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLD')


In [7]:
res = db.get_user_vectors()
print(f"type: {type(res)}")
print(f"len: {len(res)}")
print(f"res: {res[0][:100]}")

type: <class 'list'>
len: 42
res: ["/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLD


In [8]:
# Add user
data1 = np.random.rand(4, 3)
print("Original array 1:\n", data1)
user_id = db.add_user(data1)
print("User id is:", user_id)

# Modifie user
data2 = np.random.rand(4, 3)
print("Original array 2:\n", data2)
res = db.update_user(user_id, data2)
print("Number of affected rows:", res)
retrieved_array = db.get_user(user_id)
print("Both arrays not match:", data1==retrieved_array)

# Delete user
res = db.delete_user(user_id)
print("Delete user:", user_id)
print("Number of affected rows:", res)

Original array 1:
 [[0.06674492 0.70138273 0.46100755]
 [0.79150953 0.89165282 0.61386593]
 [0.42284293 0.84995265 0.11969977]
 [0.15342916 0.46183154 0.22598121]]
User id is: 49
Original array 2:
 [[0.50725915 0.92857787 0.2087178 ]
 [0.00353338 0.80896708 0.97460554]
 [0.81242094 0.37040217 0.95570088]
 [0.5319285  0.34016226 0.17376084]]
Number of affected rows: 1
Both arrays not match: [[False False False]
 [False False False]
 [False False False]
 [False False False]]
Delete user: 49
Number of affected rows: 1
